### PR TITLE
Crowdin translations Feb. 2022 update

### PR DESCRIPTION
**Pull request by horus68**
Crowdin translation general update for TemaTres 3.3.1 version
- All language files are now only the xx-XX format.
- Removing files for 2 letters code as non-necessary.
- File en-utf-8.inc.php it's the master file used for Crowdin (any new master lines should be added to this file and uploaded do Crowdin)

- For translators: please update your translations using the Crowdin project for TemaTres https://crowdin.com/project/tematres

### CODE REVIEW

**Comment by tematres** [comment]
Thank you !!!  :))

**Comment by tematres** [comment]
hi @horus68 :) the code was update to support the xx-XX format. I The english file following the xx-XX format to the english language (en-EN) was added, is better to use this file as master in crowdin or the original en-utf-8.inc.php? what do you think?

thank you in advance :)

**Comment by horus68** [comment]
you can delete the en-utf-8.inc.php and the en-EN-utf-8.inc.php will be used in Crowdin as a master (translators can't edit it).
The files en-GB-utf-8.inc.php / en-US-utf-8.inc.php can be translated using Crowdin so users from those languages can also improve the english terms

**Comment by tematres** [comment]
ok!! thanks :)

**Pull request merged**
