### PR TITLE
Fix typo for english language

### PR DESCRIPTION
**Pull request by horus68**
Some typos fixed in the english language file. 
Hope some native user can make it better!

### CODE REVIEW

**Comment by horus68** [comment]
@tematres Many language strings do not uses capital letter for its values. I don't know if by any special code option (even the software correctly outputs a capital letter on titles).
For translators its better to have any sentence/title started by a capital letter, so its easy to know when a word or text is not the start of a sentence (or a title).
If changes to the english file has to be done this will not have negative impact on actual translations on Crowdin https://crowdin.com/project/tematres so feel free to revise the file if needed.

**Comment by tematres** [comment]
mmm. Actually tematres make capital letter by code (use ucfirst() command) and all the string are in lower case. Do you think is better define de capital or lower case in source language file?

**Comment by horus68** [comment]
I don't have a strong opinion on this.
Its certainly not pleasant for translators but we can live with it!
If changes will occur they should be required only in the source language file unless there are any performance gains on not use the auto-capitalization function in the software.

But for translators its better to have a value (in the language file) started with capital letter if they are to be used as Title. 
See this one... when I started translating Tematres I never knew if I should use a capital letter or not as some english values starts with capital letter but others not (And could be a part of a sentence, not the beginning of it!).

```
define("FORM_JS_check","Please check the data of ");
define("FORM_JS_confirm","eliminate this relationship?");
```

Actually it didn't caused issues with tematres but that's something i'm a little bit alert as in Portuguese (Portugal) some special words has capitalization if starting a sentence but not if in the middle  (as in days of the week or month names). 


- With Crowdin we would gain of normalizing capitalization in the language files. The translations form Tematres main file could be used for auto-fill in other language files as TematresView or visualvocabulary, but the usage is not the same between projects that do not allow automatic fill from translation memory (they are not 100% the same!). See the word "Details"

Tematres
`define("LABEL_Detalle","details");`
TematresView
`$message[9] = "Details" ;`


Final note: I should had opened an issue to discuss this as this PR do not address the capitalization issue, only typos! :)

**Comment by horus68** [comment]
@tematres bump to be merged?

**Pull request merged**
